name: Docker Image CI

on:
  push:
    branches: [ master, php8-update ]
  pull_request:
    branches: [ master, php8-update ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grav:$(date +%s)
